
//TYPE
export const SELECT_TYPE = "SELECT_TYPE";

//MOVIES ACTIONS
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

//TV SHOWS ACTIONS
export const FETCH_TV_SHOWS = 'FETCH_TV_SHOWS';
export const FETCH_TV_SHOWS_SUCCESS = 'FETCH_TV_SHOWS_SUCCESS';
export const FETCH_TV_SHOWS_FAILURE = 'FETCH_TV_SHOWS_FAILURE';


//MOVIE DETAILS ACTIONS
export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS';
export const FETCH_MOVIE_DETAILS_FAILURE = 'FETCH_MOVIE_DETAILS_FAILURE';

//TV SHOWS DETAILS ACTIONS
export const FETCH_TV_SHOWS_DETAILS = 'FETCH_TV_SHOWS_DETAILS';
export const FETCH_TV_SHOWS_DETAILS_SUCCESS = 'FETCH_TV_SHOWS_DETAILS_SUCCESS';
export const FETCH_TV_SHOWS_DETAILS_FAILURE = 'FETCH_TV_SHOWS_DETAILS_FAILURE';


//SEARCH MOVIES ACTIONS
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';

//SEARCH TV SHOWS ACTIONS
export const SEARCH_TV_SHOWS = 'SEARCH_TV_SHOWS';
export const SEARCH_TV_SHOWS_SUCCESS = 'SEARCH_TV_SHOWS_SUCCESS';
export const SEARCH_TV_SHOWS_FAILURE = 'SEARCH_TV_SHOWS_FAILURE';
